# Site settings
title: Zahoor Mohamed's Blog
email: zahoor@zahoor.in
description: > # this means to ignore newlines until "baseurl:"
  My Blog 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "zahoor.eth" # the base hostname & protocol for your site
twitter_username: jmohamedzahoor 
github_username: jmozah    
linkedin_username: j-mohamed-zahoor-294b1020

# Build settings
markdown: kramdown
